apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-php-app
  labels:
    app: basic-php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-php-app
  template:
    metadata:
      labels:
        app: basic-php-app
    spec:
      containers:
      - name: basic-php-app
        image: chakkadocker/basic_php_dockerapp:v1
        ports:
        - containerPort: 80
