apiVersion: v1
kind: Service
metadata:
  labels:
    app: basic-php-app
  name: basic-php-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: basic-php-app
