apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-website-service
  name: my-website-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: my-website-service
